language: ruby
before_install:
  - gem install bundler
  - rm -f ${BUNDLE_GEMFILE}.lock
  - cd $TRAVIS_BUILD_DIR
before_script:
  - bundle update
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
cache: bundler
rvm:
  - 2.2.3
gemfile: gemfiles/Gemfile.travis
matrix:
  fast_finish: true
notifications:
  email:
    recipients:
      - tyler@cocoburg.com
  on_success: 'always'
  on_failure: 'always'

bundler_args: "--without production --retry 3"
services:
- memcached
- postgresql
- redis
addons:
  postgresql: '9.3'
env:
  GOOGLE_API_SERVER_KEY: 'fakekey'
