require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MeetingGroupsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # MeetingGroup. As you add validations to MeetingGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: 'Support Group'}
  }

  let(:invalid_attributes) {
    {name: ''}
  }

  let(:meeting_group) {create :meeting_group}

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MeetingGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all meeting_groups as @meeting_groups" do
      meeting_group
      get :index, {}, valid_session
      expect(assigns(:meeting_groups)).to eq([meeting_group])
    end
  end

  describe "GET #show" do
    it "assigns the requested meeting_group as @meeting_group" do

      get :show, {:id => meeting_group.to_param}, valid_session
      expect(assigns(:meeting_group)).to eq(meeting_group)
    end
  end

  describe "GET #new" do
    it "assigns a new meeting_group as @meeting_group" do
      get :new, {}, valid_session
      expect(assigns(:meeting_group)).to be_a_new(MeetingGroup)
    end
  end

  describe "GET #edit" do
    it "assigns the requested meeting_group as @meeting_group" do

      get :edit, {:id => meeting_group.to_param}, valid_session
      expect(assigns(:meeting_group)).to eq(meeting_group)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MeetingGroup" do
        expect {
          post :create, {:meeting_group => valid_attributes}, valid_session
        }.to change(MeetingGroup, :count).by(1)
      end

      it "assigns a newly created meeting_group as @meeting_group" do
        post :create, {:meeting_group => valid_attributes}, valid_session
        expect(assigns(:meeting_group)).to be_a(MeetingGroup)
        expect(assigns(:meeting_group)).to be_persisted
      end

      it "redirects to the created meeting_group" do
        post :create, {:meeting_group => valid_attributes}, valid_session
        expect(response).to redirect_to(MeetingGroup.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved meeting_group as @meeting_group" do
        post :create, {:meeting_group => invalid_attributes}, valid_session
        expect(assigns(:meeting_group)).to be_a_new(MeetingGroup)
      end

      it "re-renders the 'new' template" do
        post :create, {:meeting_group => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: 'Another Group'}
      }

      it "updates the requested meeting_group" do

        put :update, {:id => meeting_group.to_param, :meeting_group => new_attributes}, valid_session
        meeting_group.reload
        expect(meeting_group.name).to eq('Another Group')
      end

      it "assigns the requested meeting_group as @meeting_group" do

        put :update, {:id => meeting_group.to_param, :meeting_group => valid_attributes}, valid_session
        expect(assigns(:meeting_group)).to eq(meeting_group)
      end

      it "redirects to the meeting_group" do

        put :update, {:id => meeting_group.to_param, :meeting_group => valid_attributes}, valid_session
        expect(response).to redirect_to(meeting_group)
      end
    end

    context "with invalid params" do
      it "assigns the meeting_group as @meeting_group" do

        put :update, {:id => meeting_group.to_param, :meeting_group => invalid_attributes}, valid_session
        expect(assigns(:meeting_group)).to eq(meeting_group)
      end

      it "re-renders the 'edit' template" do

        put :update, {:id => meeting_group.to_param, :meeting_group => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    before {meeting_group}
    it "destroys the requested meeting_group" do

      expect {
        delete :destroy, {:id => meeting_group.to_param}, valid_session
      }.to change(MeetingGroup, :count).by(-1)
    end

    it "redirects to the meeting_groups list" do

      delete :destroy, {:id => meeting_group.to_param}, valid_session
      expect(response).to redirect_to(meeting_groups_url)
    end
  end

end
